name: Run test unit on pull request

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: run-test-unit
  cancel-in-progress: true

jobs:
  Test:
    name: Run test unit - test PR
    uses: ./.github/workflows/wc_test.yml
    with:
      xcodeversion: ${{ vars.XCODE_VERSION }}
      project_name: ${{ vars.PROJECT_NAME }}