name: Build apple preview release

on:
  release:
    types: [published]

jobs:
  getEnvironment:
    name: Chosen trigger environment
    runs-on: ubuntu-latest
    outputs:
      envProduction: ${{ steps.setEnv.outputs.value }}
      tagRelease: ${{ steps.tag.outputs.value }}
    steps:
      - name: Get pre-release asked or not
        if: ${{ github.event.release.prerelease }}
        id: prerelease
        run: |
          echo "value=true" >> $GITHUB_OUTPUT
          echo ${{ github.event.release.prerelease }}

      - name: Set environment
        id: setEnv
        run: |
          echo "value=true" >> $GITHUB_OUTPUT
          if [[ "${{ steps.prerelease.outputs.value }}" == true ]]; then
            echo "value=false" >> $GITHUB_OUTPUT
          fi
          exit 0

      - name: get tag
        id: tag
        run: echo "value=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

  NewStep:
    name: Test var
    runs-on: ubuntu-latest
    needs:
      - getEnvironment
    steps:
      - run: |
          echo ${{ needs.getEnvironment.outputs.envProduction }}
          echo ${{ needs.getEnvironment.outputs.tagRelease }}