name: Build-prerelease-gh

on:
  release:
    types: [published]

permissions:
  actions: write

jobs:
  DeletePrereeleasePipeline:
    if: github.event.release.prerelease
    name: Delete release pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto-delete
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sleep 10
          RUN_ID=$(gh run list --workflow on-tag-release.yml | grep -oh 'skipped.*' | head -1 | awk '{print $6}')
          cd ${{ github.workspace }}
          echo $RUN_ID
          gh run delete $RUN_ID
          exit 0

  NewStep:
    name: Test var
    runs-on: ubuntu-latest
    needs:
      - DeletePrereeleasePipeline
    steps:
      - run: echo "hello world"